version: '3.3'
services:
  web:
    build: .
    privileged: true
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
